"""
traduzioni.py
Dizionario centralizzato IT/EN per i testi fissi della pagina di voto e
della pagina risultati (VotoShow.py). I dati delle canzoni (titolo,
artista) restano quelli reali, non vengono tradotti.
"""

LINGUA_DEFAULT = "it"

TESTI = {
    "it": {
        "titolo_pagina_voto": "Richiedi la prossima animazione",
        "intestazione_voto": "Quale animazione vuoi vedere dopo quella che stai guardando?",
        "istruzioni_voto": "Durante l'animazione in corso puoi votare quante volte vuoi: conta solo l'ultima scelta, fino a pochi secondi dalla fine. Le animazioni richieste verranno eseguite, prima o poi, seguendo la coda generata dai voti.",
        "avviso_in_pausa_rifiutato": "Questa animazione e' stata eseguita da poco: non puoi richiederla di nuovo per un po', il voto non e' stato registrato.",
        "avviso_in_pausa_accettato": "Questa animazione e' stata eseguita da poco: non puo' partire subito, ma il tuo voto resta valido e verra' messa in coda appena possibile.",
        "avviso_coda_piena": "La coda e' al momento piena: il tuo voto conta per questo turno, ma se vince potrebbe non trovare posto in coda.",
        "etichetta_in_pausa": "in pausa",
        "bottone_vota": "Richiedi questa",
        "bottone_votato": "Richiesta inviata",
        "nessuna_canzone": "Nessuna animazione disponibile al momento.",
        "titolo_pagina_risultati": "Risultati richieste",
        "intestazione_risultati": "Risultati",
        "voti_totali": "richieste totali",
        "nessun_voto": "Nessuna richiesta ancora.",
        "colonna_classifica_live": "Classifica di questo turno",
        "colonna_coda_salvata": "In coda",
        "colonna_coda_salvata_nota_turno": "Il turno in corso sostituisce sempre quello precedente: vince chi vota adesso.",
        "colonna_coda_salvata_nota_persistente": "Le nuove richieste si aggiungono in fondo a questa lista: chi e' gia' in coda non perde il proprio posto per richieste piu' recenti.",
        "colonna_coda_salvata_nota_tetto": "Le nuove richieste si aggiungono in fondo a questa lista, fino a un massimo di {tetto} posizioni: oltre quel limite non entrano.",
        "modalita_coda_label": "Modalita' coda:",
        "modalita_coda_nome_turno": "Sempre l'ultimo turno (nessuna coda)",
        "modalita_coda_nome_persistente": "Coda senza limiti",
        "modalita_coda_nome_tetto": "Coda con tetto massimo ({tetto} posizioni)",
        "coda_vuota": "Nessuna sequenza in coda al momento.",
        "colonna_vincente": "Ha vinto ed e' in onda ora",
        "colonna_vincente_nota": "La classifica di richieste che ha fatto partire la sequenza attuale.",
        "nessuna_vincente": "Nessuna sequenza vinta per richieste al momento.",
        "bottone_reset": "Nuovo turno (azzera richieste)",
        "conferma_reset": "Azzerare le richieste per iniziare un nuovo turno?",
        "voti_suffisso": "richieste",
        "pagina_login_titolo": "Accesso amministratore",
        "pagina_login_istruzioni": "Inserisci la password per vedere i risultati.",
        "pagina_login_bottone": "Accedi",
        "pagina_login_errore": "Password errata.",

        # --- Pagina di benvenuto (VotoShow.py, prima della pagina di voto) ---
        "bv_titolo_pagina": "Benvenuti",
        "bv_bottone_vota": "Continua",
        "bv_bottone_ascolta": "🔊 Ascolta",
        "bv_bottone_pausa": "⏸ Metti in pausa",

        # --- Pagina menu (VotoShow.py, bivio tra saluto e voto) ---
        "hub_titolo_pagina": "Cosa vuoi fare?",
        "hub_intro": "Scegli cosa fare: puoi fare anche entrambe le cose, una dopo l'altra.",
        "hub_bottone_saluto": "🎅 Fai salutare il tuo bambino",
        "hub_bottone_vota": "🎵 Scegli la tua animazione preferita",
        "hub_link_info": "❤️ Beneficenza",

        # --- Pagina Info (VotoShow.py, contenuto libero configurabile da ManagerShow) ---
        "info_titolo_pagina": "Beneficenza",
        "info_testo_placeholder": "Questa pagina e' dedicata alla beneficenza - presto qui troverai come contribuire! Torna a trovarci. 🎄",
        "info_bottone_dona": "❤️ Dona ora",

        # --- Pagina di ringraziamento post-donazione (VotoShow.py) ---
        "grazie_titolo_pagina": "Grazie!",
        "grazie_testo_default": "Grazie di cuore per il tuo contributo! ❤️ Significa molto per noi e per chi aiutiamo.",

        # --- Pagina-ponte prima del voto (VotoShow.py) ---
        "vi_titolo_pagina": "Come funziona il voto",
        "vi_testo": "Vota la canzone che vuoi vedere animata! E' un voto pubblico: alla fine di ogni turno parte quella piu' votata da tutti. Il tuo voto conta, ma non e' una richiesta garantita immediata 😊",
        "vi_bottone_continua": "Vai al voto",
        "vi_bottone_indietro": "← Torna al menu",

        # --- Pagina-ponte prima del saluto di Babbo Natale (VotoShow.py) ---
        "sg_titolo_pagina": "Il saluto di Babbo Natale",
        "sg_testo": "Scrivi il nome del tuo bambino: Babbo Natale lo salutera' per nome con luci e voce, dopo la sequenza in corso o quella successiva! Tutto viene generato al momento da un computer dedicato: in rari casi potrebbero esserci piccoli intoppi tecnici fuori dal nostro controllo. Grazie per la pazienza, buon Natale! 🎄",
        "sg_bottone_continua": "Scrivi il nome",
        "sg_bottone_indietro": "← Torna al menu",

        # --- Pagina raccolta nome per il saluto (VotoShow.py, placeholder) ---
        "sn_titolo_pagina": "Il saluto di Babbo Natale",
        "sn_etichetta_nome": "Nome del bambino/a:",
        "sn_bottone_invia": "Invia",
        "sn_confermato_testo": "Grazie! 🎅 Il saluto per {nome} e' stato richiesto.",
        "sn_confermato_nota": "(Funzionalita' ancora in costruzione: per ora la richiesta non viene ancora elaborata davvero.)",
        "sn_bottone_aggiungi_altro": "Saluta un altro bambino",
        "sn_bottone_vai_voto": "Vai al voto",
        "sn_bottone_torna_menu": "Torna al menu",

        # --- CostruisciCatalogo.py (console) ---
        "cc_errore_mutagen": "ERRORE: manca il pacchetto 'mutagen'.\nInstallalo con:  pip install mutagen\npoi rilancia questo script.",
        "cc_chiedi_installazione": "Vuoi che lo installi ora automaticamente? (s/n): ",
        "cc_installazione_riuscita": "'mutagen' installato correttamente. Rilancia questo script.",
        "cc_installazione_fallita": "Installazione automatica fallita. Prova a mano con: pip install mutagen",
        "cc_errore_config_mancante": "ERRORE: file di configurazione non trovato: {percorso}",
        "cc_errore_cartella_sequenze_non_configurata": "ERRORE: Cartella_Sequenze non configurata in [PERCORSI]",
        "cc_errore_cartella_sequenze_non_trovata": "ERRORE: Cartella_Sequenze non trovata: {percorso}",
        "cc_errore_lettura_tag": "  ! Impossibile leggere i tag di '{nome}': {errore}",
        "cc_nessun_audio": "  ! '{nome}': nessun file audio trovato, sequenza saltata",
        "cc_nessuna_copertina": "  ! '{nome}': nessuna copertina trovata, verra' mostrata senza immagine",
        "cc_scansione_di": "Scansione di: {percorso}",
        "cc_cartella_esclusa": "  - '{nome}' esclusa dal voto (da configurazione)",
        "cc_cartella_nome": "  - '{nome}'",
        "cc_catalogo_salvato": "\nCatalogo salvato in: {percorso}",
        "cc_canzoni_votabili": "Canzoni richiedibili: {numero}",
        "cc_attenzione_senza_copertina": "\nAttenzione, senza copertina (aggiungine una nella cartella e rilancia):",

        # --- GestisciCanzoni.pyw (GUI) ---
        "gc_dipendenza_mancante_titolo": "Dipendenza mancante",
        "gc_dipendenza_mancante_testo": "Manca il pacchetto 'mutagen'.\n\nVuoi installarlo ora automaticamente (consigliato)?\n\nVerra' installato per lo stesso Python che hai usato per aprire questa finestra, cosi' non ci sono ambiguita' tra piu' installazioni di Python sul PC.",
        "gc_installazione_riuscita_titolo": "Installazione completata",
        "gc_installazione_riuscita_testo": "'mutagen' installato correttamente.\n\nChiudi e riapri questa finestra per continuare.",
        "gc_installazione_fallita_titolo": "Installazione fallita",
        "gc_installazione_fallita_testo": "Non sono riuscito a installare 'mutagen' automaticamente:\n\n{errore}\n\nProva manualmente da Prompt dei comandi con:\npip install mutagen",
        "gc_conferma_rinomina_titolo": "Conferma rinomina",
        "gc_conferma_rinomina_testo": "Rinominare '{vecchio}' in '{nuovo}'?\n\nTrigger LOR ed eventuale esclusione dal voto verranno spostati automaticamente sul nuovo nome.",
        "gc_titolo_finestra": "Gestisci canzoni votabili",
        "gc_titolo_dialogo_modifica": "Modifica canzone",
        "gc_titolo_dialogo_aggiungi": "Aggiungi nuova canzone",
        "gc_campo_nome": "Nome (cartella):",
        "gc_campo_audio": "File audio:",
        "gc_nessuno_scelto": "(nessuno scelto)",
        "gc_sfoglia_audio": "Sfoglia audio...",
        "gc_campo_titolo": "Titolo:",
        "gc_campo_artista": "Artista:",
        "gc_campo_copertina": "Copertina:",
        "gc_nessuna": "(nessuna)",
        "gc_sfoglia_copertina": "Sfoglia copertina...",
        "gc_campo_trigger": "Trigger LOR (Network-Unit-Input):",
        "gc_campo_nome_lor": "Nome in LOR (esatto, per il voto):",
        "gc_bottone_carica_da_lor": "Carica da LOR",
        "gc_lor_non_raggiungibile_titolo": "LOR non raggiungibile",
        "gc_lor_non_raggiungibile_testo": "Impossibile contattare l'API di LOR (deve essere aperto, anche senza schede collegate):\n{errore}",
        "gc_lor_nessuna_sequenza_titolo": "Nessuna sequenza trovata",
        "gc_lor_nessuna_sequenza_testo": "LOR non ha restituito nessuna sequenza nel Main. Verifica che lo show sia caricato.",
        "gc_bottone_annulla": "Annulla",
        "gc_bottone_chiudi": "Chiudi",
        "gc_bottone_salva": "Salva",
        "gc_scegli_audio": "Scegli il file audio",
        "gc_scegli_copertina": "Scegli la copertina",
        "gc_filtro_audio": "File audio",
        "gc_filtro_immagini": "Immagini",
        "gc_filtro_tutti": "Tutti i file",
        "gc_errore_campo_obbligatorio": "Campo obbligatorio",
        "gc_errore_nome_vuoto": "Il nome non puo' essere vuoto.",
        "gc_errore_titolo_vuoto": "Il titolo non puo' essere vuoto.",
        "gc_nome_gia_usato_titolo": "Nome gia' usato",
        "gc_nome_gia_usato_testo": "Esiste gia' una cartella chiamata '{nome}'.",
        "gc_audio_mancante_titolo": "File audio mancante",
        "gc_audio_mancante_testo": "Scegli un file audio prima di salvare.",
        "gc_salvato_con_avvisi_titolo": "Salvato con avvisi",
        "gc_salvato_con_avvisi_testo": "Canzone salvata, ma la rigenerazione del catalogo ha dato un problema:\n{errore}",
        "gc_promemoria_titolo": "Promemoria trigger LOR",
        "gc_promemoria_testo": "Ricordati di creare/aggiornare in LOR Show Player (Interactive Group) un trigger con indirizzo:\n\n{trigger}\n\ncollegato alla sequenza .loredit di '{titolo}'.\nSe il file .loredit non e' ancora nella cartella '{nome}', aggiungilo tu a parte.",
        "gc_errore_titolo": "Errore",
        "gc_errore_salvataggio_file": "Errore salvando i file: {errore}",
        "gc_colonna_numero": "N.",
        "gc_colonna_titolo": "Titolo",
        "gc_colonna_artista": "Artista",
        "gc_colonna_durata": "Durata",
        "gc_colonna_trigger": "Trigger LOR",
        "gc_colonna_nome_lor": "Nome in LOR",
        "gc_colonna_stato": "Stato",
        "gc_bottone_aggiorna_lista": "Aggiorna lista",
        "gc_bottone_aggiungi": "Aggiungi nuova...",
        "gc_bottone_modifica": "Modifica selezionata...",
        "gc_bottone_escludi_includi": "Escludi/Includi selezionata",
        "gc_bottone_rigenera": "Rigenera catalogo ora",
        "gc_bottone_apri_voto": "Voto",
        "gc_bottone_apri_risultati": "Apri risultati",
        "gc_bottone_apri_benvenuto": "Benvenuto",
        "gc_bottone_test_multi_voto": "Test multi-voto",
        "gc_lingua_bottone": "EN",
        "ms_bottone_salva_ordine_schede": "Salva ordine schede",
        "ms_ordine_schede_salvato_testo": "Ordine delle schede salvato: verra' ripristinato ai prossimi avvii.",
        "gc_stato_senza_audio": "Senza audio",
        "gc_stato_esclusa": "Esclusa",
        "gc_stato_votabile": "Richiedibile",
        "gc_cartella_non_trovata_titolo": "Cartella sequenze non trovata",
        "gc_cartella_non_trovata_testo": "Cartella_Sequenze non esiste:\n{percorso}",
        "gc_nessuna_selezione_titolo": "Nessuna selezione",
        "gc_nessuna_selezione_testo": "Seleziona prima una canzone dalla lista.",
        "gc_non_modificabile_titolo": "Non modificabile",
        "gc_non_modificabile_testo": "Questa voce non ha un file audio da modificare.",
        "gc_conferma_esclusione_titolo": "Conferma esclusione",
        "gc_conferma_esclusione_testo": "Escludere '{nome}' dal voto?\n\nI file audio/.loredit restano intatti sul disco: potrai reincluderla quando vuoi.",
        "gc_azione_inclusa": "inclusa nel voto",
        "gc_azione_esclusa": "esclusa dal voto",
        "gc_attenzione_titolo": "Attenzione",
        "gc_attenzione_testo": "'{nome}' {azione}, ma la rigenerazione del catalogo ha dato un problema:\n{errore}",
        "gc_fatto_titolo": "Fatto",
        "gc_fatto_testo": "Catalogo rigenerato. Riavvia VotoShow.py se era gia' in esecuzione durante lo show.",
        "gc_rigenerazione_fallita": "Rigenerazione catalogo fallita:\n{errore}",
        "gc_errore_config_generico": "Errore nella configurazione (vedi CONFIGURAZIONE_SHOW.ini).",

        # --- ManagerShow.pyw, scheda Programmazione ---
        "ms_titolo_finestra": "Manager Show",
        "ms_scheda_canzoni": "Canzoni",
        "ms_scheda_programmazione": "Programmazione",
        "ms_scheda_saluto_babbonatale": "Saluto Babbo Natale",
        "ms_titolo_stato_attuale": "Stato attuale",
        "ms_stato_in_esecuzione": "in esecuzione",
        "ms_stato_fermo": "fermo",
        "ms_stato_motore_concluso": "controllo gia' concluso (normale, si chiude da solo)",
        "ms_bottone_aggiorna_stato": "Aggiorna stato",
        "ms_titolo_orari": "Orari",
        "ms_campo_accensione": "Orario Accensione del sistema di voto (uguale o qualche minuto prima di quello programmato in LOR):",
        "ms_campo_spegnimento": "Orario Spegnimento del sistema di voto (uguale o qualche minuto dopo quello programmato in LOR):",
        "ms_titolo_giorni": "Giorni Attivi",
        "ms_giorno_0": "Lun", "ms_giorno_1": "Mar", "ms_giorno_2": "Mer", "ms_giorno_3": "Gio",
        "ms_giorno_4": "Ven", "ms_giorno_5": "Sab", "ms_giorno_6": "Dom",
        "ms_titolo_pulizia": "Pulizia automatica pre-show LOR - pre-voto (chiude Chrome, svuota temp/cache)",
        "ms_campo_minuti_anticipo": "Minuti di anticipo su Orario Accensione (VotoShow e MotoreShow, non LOR):",
        "ms_bottone_pulisci_ora": "Pulisci ora",
        "ms_titolo_stato_pianificazione": "Pianificazione automatica (Windows)",
        "ms_bottone_salva_orari": "Salva orari",
        "ms_salva_orari_promemoria_testo": "Orari salvati. Ricorda: se vuoi che Windows li tenga in considerazione e li applichi in automatico, devi premere \"Pianifica Win Auto\" qui a lato - salvare da solo non basta.",
        "ms_bottone_applica": "Pianifica Win Auto",
        "ms_bottone_rimuovi": "Rimuovi Win Auto",
        "ms_bottone_avvia_ora": "Avvia ora",
        "ms_bottone_ferma_ora": "Stop ora",
        "ms_avviso_avvia_ferma_testo": "Avvia ora/Stop ora agiscono solo subito, dal vivo: non toccano la pianificazione automatica di Windows, che resta quella impostata nel box Orari.",
        "ms_bottone_guida": "Guida",
        "ms_bottone_guida_pulizia": "Guida pulizia",
        "ms_titolo_chiudi_chrome": "Chiudi Chrome",
        "ms_titolo_pulisci_cache": "Svuota file temporanei e cache di Chrome",
        "ms_titolo_blocca_aggiornamenti": "Blocca Windows Update",
        "ms_avviso_no_admin_titolo": "ManagerShow non elevato: blocco automatico non garantito",
        "ms_avviso_no_admin_testo": "Pianificazione creata (con i permessi normali, per evitare l'errore 'Accesso negato'), ma il blocco automatico di Windows Update NON funzionera': serve che ManagerShow.pyw sia avviato con 'Esegui come amministratore' proprio nel momento in cui premi questo pulsante - non basta che l'account sia amministratore, va elevato ogni volta. Gli aggiornamenti resteranno quindi automatici come sempre e potrebbero scattare anche durante lo show.\n\nPer essere sicuro: vai tu stesso in Impostazioni > Windows Update > Sospendi aggiornamenti, a mano, almeno 2-3 ore prima dell'Orario Accensione - oppure chiudi ManagerShow e riaprilo con tasto destro > Esegui come amministratore, poi ripeti \"Pianifica Win Auto\".",
        "ms_label_programmi_extra": "Programmi da chiudere in automatico:",
        "ms_titolo_programmi_extra": "Programmi da chiudere",
        "ms_istruzioni_programmi_extra": "Premi \"Sfoglia...\" e cerca il programma da chiudere durante la pulizia (nella cartella Programmi, o dove lo hai installato, anche su un altro disco). Questi programmi vengono chiusi sia dalla pulizia automatica che da \"Pulisci ora\".",
        "ms_bottone_sfoglia_programma": "Sfoglia...",
        "ms_filtro_eseguibili": "Programmi (*.exe)",
        "ms_bottone_apri_gestione_programmi": "Aggiungi...",
        "ms_bottone_aggiungi_singolo": "Aggiungi",
        "ms_bottone_rimuovi_programma": "Rimuovi",
        "ms_errore_orario_titolo": "Orario non valido",
        "ms_errore_orario_accensione_testo": "Orario Accensione deve essere HH:MM (es. 17:30).",
        "ms_errore_orario_spegnimento_testo": "Orario Spegnimento deve essere HH:MM (es. 22:30).",
        "ms_errore_nessun_giorno_titolo": "Nessun giorno selezionato",
        "ms_errore_nessun_giorno_testo": "Seleziona almeno un giorno attivo.",
        "ms_errore_minuti_titolo": "Valore non valido",
        "ms_errore_minuti_testo": "Minuti di anticipo deve essere un numero (es. 15).",
        "ms_conferma_titolo": "Conferma",
        "ms_pianificazione_applicata_testo": "Pianificazione applicata: pulizia alle {orario}, sistema di voto acceso/spento agli orari impostati.",
        "ms_pianificazione_fallita_testo": "Non sono riuscito a registrare la pianificazione:\n\n{dettagli}",
        "ms_prefisso_avvio": "Avvio",
        "ms_prefisso_stop": "Stop",
        "ms_prefisso_pulizia": "Pulizia",
        "ms_conferma_rimozione_testo": "Rimuovere la pianificazione automatica? Dovrai avviare/fermare tutto a mano.",
        "ms_pianificazione_rimossa_testo": "Pianificazione rimossa.",
        "ms_stato_pianificazione_attiva": "Pianificazione di Windows ATTIVA: pulizia, avvio e arresto del sistema di voto automatici.",
        "ms_stato_pianificazione_non_attiva": "Pianificazione di Windows NON attiva: avvio/arresto solo manuale.",
        "ms_pulizia_eseguita_testo": "Pulizia eseguita (Chrome chiuso, file temporanei/cache svuotati, se abilitato).",

        # --- ManagerShow.pyw, scheda Programmazione: modalita' coda voti ---
        "ms_titolo_modalita_coda": "Modalita' coda voti",
        "ms_modalita_coda_label": "Come gestire la coda:",
        "ms_modalita_coda_turno": "Sempre l'ultimo turno (nessuna coda)",
        "ms_modalita_coda_persistente": "Coda senza limiti (mai scartata)",
        "ms_modalita_coda_tetto": "Coda con tetto massimo",
        "ms_tetto_coda_label": "Tetto massimo (posizioni in coda):",
        "ms_nota_modalita_coda_turno": "Nessuna coda: vince solo chi vota adesso, chi perde un turno non vede mai partire la propria scelta se il pubblico continua a votare. Richiede il riavvio di VotoShow.py.",
        "ms_nota_modalita_coda_persistente": "Chi vince un turno non viene mai scartato da voti piu' recenti, ma in serate molto votate l'attesa puo' allungarsi parecchio. Richiede il riavvio di VotoShow.py.",
        "ms_nota_modalita_coda_tetto": "Via di mezzo: l'attesa massima resta limitata al tetto scelto qui sotto, oltre quel limite i turni in eccesso non si accodano. Richiede il riavvio di VotoShow.py.",
        "ms_bottone_salva_modalita_coda": "Salva modalita' coda",
        "ms_modalita_coda_salvata_testo": "Modalita' coda salvata. Riavvia VotoShow.py (Stop ora / Avvia ora) perche' abbia effetto.",
        "ms_modalita_coda_riavvia_ora_titolo": "Riavviare VotoShow.py ora?",
        "ms_modalita_coda_riavvia_ora_testo": "VotoShow.py e' in esecuzione. Vuoi riavviarlo subito per applicare la nuova modalita' di coda?\n\nDurante il riavvio (pochi secondi) il servizio di voto sara' irraggiungibile per gli ospiti.",
        "ms_modalita_coda_riavviato_testo": "Modalita' coda salvata e VotoShow.py riavviato: la nuova modalita' e' gia' attiva.",
        "ms_errore_tetto_titolo": "Valore non valido",
        "ms_errore_tetto_testo": "Il tetto massimo deve essere un numero intero di almeno 1.",
        "ms_raffreddamento_label": "Raffreddamento (pausa dopo la messa in onda):",
        "ms_raffreddamento_turni": "Numero di sequenze",
        "ms_raffreddamento_minuti": "Minuti",
        "ms_raffreddamento_valore_label": "Valore:",
        "ms_errore_raffreddamento_titolo": "Valore non valido",
        "ms_errore_raffreddamento_testo": "Il valore del raffreddamento deve essere un numero intero di almeno 1.",
        "ms_avviati_testo": "VotoShow.py e MotoreShow.py avviati (se non erano gia' in esecuzione).",
        "ms_fermati_testo": "VotoShow.py e MotoreShow.py fermati (se erano in esecuzione).",

        # --- ManagerShow.pyw, scheda Programmazione: saluto di Babbo Natale (opzionale) ---
        "ms_titolo_saluto_babbonatale": "Saluto di Babbo Natale (opzionale)",
        "ms_checkbox_saluto_babbonatale": "Abilita il saluto personalizzato per nome",
        "ms_nota_saluto_babbonatale": "Funzione facoltativa: se disattivata, gli ospiti vedono solo la pagina di voto, senza nessun bivio. Se attivata, prima del voto compare una scelta in piu' che permette di far scrivere il nome del proprio bambino e ricevere un saluto personalizzato (luci + voce) da Babbo Natale. ATTENZIONE: al momento questa e' solo l'interruttore e l'interfaccia - la generazione vera del saluto (l'animazione con il nome e l'audio) e' ancora in sviluppo, richiede un servizio esterno di sintesi vocale (es. ElevenLabs) da configurare a parte. Vedi il pulsante Guida per i dettagli.",
        "ms_bottone_salva_saluto_babbonatale": "Salva impostazione saluto",
        "ms_saluto_babbonatale_salvata_testo": "Impostazione salvata. Riavvia VotoShow.py (Stop ora / Avvia ora) perche' abbia effetto.",
        "ms_saluto_babbonatale_riavvia_ora_titolo": "Riavviare VotoShow.py ora?",
        "ms_saluto_babbonatale_riavvia_ora_testo": "VotoShow.py e' in esecuzione. Vuoi riavviarlo subito per applicare la nuova impostazione?\n\nDurante il riavvio (pochi secondi) il servizio di voto sara' irraggiungibile per gli ospiti.",
        "ms_saluto_babbonatale_riavviato_testo": "Impostazione salvata e VotoShow.py riavviato: e' gia' attiva.",

        # --- ManagerShow.pyw, scheda Programmazione: token amministratore ---
        "ms_titolo_token_admin": "Token amministratore",
        "ms_label_token_admin": "Token:",
        "ms_bottone_mostra_token": "Mostra",
        "ms_bottone_nascondi_token": "Nascondi",
        "ms_bottone_genera_token": "Genera casuale",
        "ms_nota_token_admin": "Serve per proteggere le pagine /risultati e /reset del server di voto (visibili sulla WiFi ospiti). Se lasciato vuoto, chiunque sulla rete puo' accedervi senza password: sconsigliato. Usa 'Genera casuale' per crearne uno robusto, poi salva. Dopo il salvataggio serve riavviare VotoShow.py perche' il nuovo token abbia effetto.",
        "ms_bottone_salva_token": "Salva token",
        "ms_token_admin_vuoto_titolo": "Salvare senza token?",
        "ms_token_admin_vuoto_testo": "Il campo e' vuoto: /risultati e /reset resteranno accessibili a chiunque sulla WiFi ospiti, senza password. Vuoi salvare comunque?",
        "ms_token_admin_salvato_testo": "Token salvato. Riavvia VotoShow.py (Stop ora / Avvia ora) perche' abbia effetto.",
        "ms_token_admin_riavvia_ora_titolo": "Riavviare VotoShow.py ora?",
        "ms_token_admin_riavvia_ora_testo": "VotoShow.py e' in esecuzione. Vuoi riavviarlo subito per applicare il nuovo token?\n\nDurante il riavvio (pochi secondi) il servizio di voto sara' irraggiungibile per gli ospiti.",
        "ms_token_admin_riavviato_testo": "Token salvato e VotoShow.py riavviato: e' gia' attivo.",

        # --- Test multi-voto (apre piu' finestre isolate per simulare piu' elettori) ---
        "ms_test_voto_titolo_dialogo": "Test multi-voto",
        "ms_test_voto_prompt": "Quante finestre vuoi aprire per il test? (ognuna conta come un elettore diverso)",
        "ms_test_voto_richiede_avvio_titolo": "VotoShow.py non e' in esecuzione",
        "ms_test_voto_richiede_avvio_testo": "Avvia prima VotoShow.py (\"Avvia ora\") per poter aprire le finestre di test.",
        "ms_test_voto_browser_non_trovato_titolo": "Browser non trovato",
        "ms_test_voto_browser_non_trovato_testo": "Non ho trovato Google Chrome o Microsoft Edge installati in un percorso standard: servono per aprire finestre con profili separati (cookie indipendenti tra loro). Installane uno dei due, oppure apri manualmente piu' browser diversi per il test.",
        "ms_test_voto_aperte_testo": "Aperte {numero} finestre di test su http://127.0.0.1:{porta}/vota, ciascuna con cookie propri (elettore separato). Il limite anti-spam di 2 secondi tra un voto e l'altro e' disattivato solo per queste finestre locali.",

        # --- ManagerShow.pyw, scheda Pagina di Benvenuto ---
        "ms_scheda_benvenuto": "Pagina di Benvenuto",
        "ms_tooltip_percorso_schede_luci": "Indica dove si trova SchedeLuci.pyw, se hai spostato la sua cartella.",
        "ms_bv_nota_scheda": "Questa e' la prima pagina che vedono gli ospiti (es. reindirizzati qui dal Wi-Fi), prima di arrivare al voto vero e proprio. Tutti i campi sono opzionali.",
        "ms_bv_titolo_testo": "Testo",
        "ms_bv_nota_testo": "Lascia una riga vuota tra due blocchi di testo per creare paragrafi separati, con la loro spaziatura (es. un titolo e sotto, staccato, un sottotitolo). Un solo invio dentro lo stesso blocco resta un semplice a-capo.",
        "ms_bv_titolo_immagine": "Immagine di sfondo",
        "ms_bv_campo_immagine": "File immagine:",
        "ms_bv_bottone_sfoglia_immagine": "Sfoglia...",
        "ms_bv_bottone_rimuovi_immagine": "Rimuovi",
        "ms_bv_scegli_immagine_titolo": "Scegli l'immagine di sfondo",
        "ms_bv_filtro_immagini": "Immagini (*.jpg;*.jpeg;*.png;*.gif)",
        "ms_bv_titolo_audio": "Audio (opzionale)",
        "ms_bv_campo_audio": "File audio:",
        "ms_bv_bottone_sfoglia_audio": "Sfoglia...",
        "ms_bv_bottone_rimuovi_audio": "Rimuovi",
        "ms_bv_scegli_audio_titolo": "Scegli il file audio",
        "ms_bv_filtro_audio": "Audio (*.mp3)",
        "ms_bv_nessuna_scelta": "(nessuno scelto)",
        "ms_bv_titolo_colore": "Colore fascia testo",
        "ms_bv_bottone_cambia_colore": "Cambia colore...",
        "ms_bv_nota_colore": "Proposto automaticamente dall'immagine scelta (se hai Pillow installato); puoi comunque cambiarlo a mano.",
        "ms_bv_bottone_salva": "Salva pagina di benvenuto",
        "ms_bv_bottone_anteprima": "Apri anteprima nel browser",
        "ms_bv_salvato_titolo": "Salvato",
        "ms_bv_salvato_testo": "Pagina di benvenuto salvata. Se VotoShow.py e' gia' in esecuzione durante lo show, riavvialo (Stop ora / Avvia ora nella scheda Programmazione) perche' le modifiche abbiano effetto.",
        "ms_bv_pillow_mancante_titolo": "Dipendenza opzionale mancante",
        "ms_bv_pillow_mancante_testo": "Per proporre automaticamente un colore preso dall'immagine serve il pacchetto 'Pillow' (non e' obbligatorio: puoi comunque scegliere il colore a mano con 'Cambia colore...').\n\nVuoi installarlo ora automaticamente?\n\nVerra' installato per lo stesso Python che hai usato per aprire questa finestra.",
        "ms_bv_pillow_installata_testo": "'Pillow' installato correttamente. Scegli di nuovo l'immagine per far proporre il colore.",

        # --- ManagerShow.pyw, scheda Info (pagina libera raggiungibile dal menu, es. per beneficenza/sponsor/regolamento) ---
        "ms_scheda_info": "Beneficenza",
        "ms_inf_nota_scheda": "Pagina facoltativa raggiungibile dal menu ospiti (link \"❤️ Beneficenza\"): usala per quello che vuoi - un link per una donazione, un ente benefico, uno sponsor, le regole dello show, ecc. Stessa struttura della pagina di Benvenuto (testo, immagine, audio), ma pensata per essere riconsultata quando serve, non solo vista una volta all'ingresso. Se lasci tutti i campi vuoti, il link scompare del tutto per gli ospiti.",
        "ms_inf_titolo_testo": "Testo",
        "ms_inf_nota_testo": "Lascia una riga vuota tra due blocchi di testo per creare paragrafi separati, con la loro spaziatura. Un solo invio dentro lo stesso blocco resta un semplice a-capo.",
        "ms_inf_titolo_immagine": "Immagine",
        "ms_inf_campo_immagine": "File immagine:",
        "ms_inf_bottone_sfoglia_immagine": "Sfoglia...",
        "ms_inf_bottone_rimuovi_immagine": "Rimuovi",
        "ms_inf_scegli_immagine_titolo": "Scegli l'immagine",
        "ms_inf_filtro_immagini": "Immagini (*.jpg;*.jpeg;*.png;*.gif)",
        "ms_inf_titolo_audio": "Audio (opzionale)",
        "ms_inf_campo_audio": "File audio:",
        "ms_inf_bottone_sfoglia_audio": "Sfoglia...",
        "ms_inf_bottone_rimuovi_audio": "Rimuovi",
        "ms_inf_scegli_audio_titolo": "Scegli il file audio",
        "ms_inf_filtro_audio": "Audio (*.mp3)",
        "ms_inf_titolo_colore": "Colore fascia testo",
        "ms_inf_bottone_cambia_colore": "Cambia colore...",
        "ms_inf_nota_colore": "Proposto automaticamente dall'immagine scelta (se hai Pillow installato); puoi comunque cambiarlo a mano.",
        "ms_inf_titolo_visibilita": "Visibilita'",
        "ms_inf_checkbox_visibile": "Pagina visibile agli ospiti (link \"❤️ Beneficenza\" nel menu)",
        "ms_inf_nota_visibilita": "Unico interruttore che conta: se spuntata, il link compare per gli ospiti anche se non hai ancora scritto nulla (vedranno un messaggio generico \"pagina in arrivo\"). Se NON spuntata, il link resta nascosto del tutto, qualunque cosa tu abbia gia' compilato qui sotto - comodo per preparare i contenuti con calma prima di pubblicarli.",
        "ms_inf_titolo_donazione": "Link donazione",
        "ms_inf_campo_link_donazione": "URL pagina di pagamento (Stripe, PayPal, altro):",
        "ms_inf_nota_donazione": "Se compilato, sulla pagina Beneficenza compare un pulsante \"❤️ Dona ora\" che porta a questo indirizzo (si apre in una nuova scheda). Il modo piu' semplice per averne uno senza scrivere codice: un 'Payment Link' di Stripe o un link 'PayPal.me' - li crei dal sito del servizio scelto e incolli qui l'URL che ti danno. Per qualcosa di piu' su misura (pagina di pagamento personalizzata, tracciamento, ecc.) serve invece scrivere codice: se non sei pratico, farti aiutare da un'AI (es. Claude, ChatGPT) per questa parte e' un ottimo modo per cavarsela comunque, spiegando cosa vuoi ottenere. Vedi il pulsante Guida per i dettagli su Stripe/PayPal.",
        "ms_inf_titolo_grazie": "Pagina di ringraziamento",
        "ms_inf_nota_grazie": "Testo mostrato dopo la donazione, su una pagina a parte (indirizzo /grazie) - utile se il servizio di pagamento scelto permette di impostare un indirizzo di ritorno personalizzato dopo il pagamento (Stripe Checkout e PayPal lo permettono entrambi). Se lasci il campo vuoto, viene mostrato un messaggio di ringraziamento generico gia' pronto. Segue la stessa spunta \"Visibile\" qui sopra - nessuna spunta separata.",
        "ms_inf_bottone_anteprima_grazie": "Apri anteprima ringraziamento",
        "ms_inf_bottone_salva": "Salva pagina Beneficenza",
        "ms_inf_bottone_anteprima": "Apri anteprima nel browser",
        "ms_inf_salvato_titolo": "Salvato",
        "ms_inf_salvato_testo": "Pagina Beneficenza salvata. Se VotoShow.py e' gia' in esecuzione durante lo show, riavvialo (Stop ora / Avvia ora nella scheda Programmazione) perche' le modifiche abbiano effetto.",

        # --- ManagerShow.pyw, scheda QR Code ---
        "ms_scheda_qrcode": "QR Code",
        "ms_qr_nota_scheda": "Genera due QR code pronti da stampare vicino allo show: uno per collegarsi al WiFi ospiti (il telefono lo fa da solo, senza scrivere password a mano), uno per aprire subito la pagina di voto. Tutto creato sul tuo PC, nessun sito esterno coinvolto: la password WiFi non esce mai da qui.",
        "ms_qr_titolo_wifi": "WiFi ospiti",
        "ms_qr_campo_ssid": "Nome rete (SSID):",
        "ms_qr_campo_password": "Password:",
        "ms_qr_campo_sicurezza": "Sicurezza:",
        "ms_qr_sicurezza_wpa": "WPA/WPA2",
        "ms_qr_sicurezza_wep": "WEP",
        "ms_qr_sicurezza_nessuna": "Nessuna (rete aperta)",
        "ms_qr_titolo_indirizzo": "Indirizzo pagina di voto",
        "ms_qr_campo_ip": "Indirizzo IP:",
        "ms_qr_nota_ip": "Rilevato in automatico dalla rete di questo PC - se hai piu' schede di rete e non e' quello giusto, correggilo a mano. Deve essere l'IP che gli ospiti raggiungono dalla rete WiFi, non 127.0.0.1.",
        "ms_qr_bottone_rileva_ip": "Rileva di nuovo",
        "ms_qr_bottone_genera": "Genera QR Code",
        "ms_qr_bottone_salva_wifi": "Salva immagine WiFi...",
        "ms_qr_bottone_salva_voto": "Salva immagine Voto...",
        "ms_qr_titolo_cartello": "Cartello stampabile",
        "ms_qr_campo_cartello_titolo": "Titolo:",
        "ms_qr_campo_cartello_sottotitolo": "Sottotitolo:",
        "ms_qr_checkbox_cartello_includi_voto": "Includi il QR della pagina voto (passo 2)",
        "ms_qr_bottone_genera_cartello": "Genera cartello stampabile",
        "ms_qr_bottone_stampa_cartello": "Stampa cartello",
        "ms_qr_dipendenza_stampa_mancante_testo": "La stampa diretta richiede il pacchetto 'pywin32'.\n\nVuoi installarlo ora automaticamente?\n\nVerra' installato per lo stesso Python usato per aprire questa finestra.",
        "ms_qr_conferma_stampa_titolo": "Stampare ora?",
        "ms_qr_conferma_stampa_testo": "Ti si e' appena aperta un'anteprima del cartello. Se va bene, verra' stampato sulla stampante predefinita: {stampante}.\n\nVuoi procedere?",
        "ms_qr_stampa_titolo": "Stampa inviata",
        "ms_qr_stampa_inviata_testo": "Il cartello e' stato inviato a {stampante}.",
        "ms_qr_cartello_sottotitolo_default": "Richiedi la tua sequenza animata preferita!",
        "ms_qr_cartello_passo1": "1. Collegati al Wi-Fi",
        "ms_qr_cartello_passo2": "2. Scegli la sequenza",
        "ms_qr_cartello_rete": "Rete: {rete}",
        "ms_qr_cartello_password": "Password: {password}",
        "ms_qr_cartello_nota_wifi": "(scansiona questo per primo)",
        "ms_qr_cartello_nota_voto": "(scansiona questo dopo esserti collegato al Wi-Fi)",
        "ms_qr_cartello_anteprima_titolo": "Va bene cosi'?",
        "ms_qr_cartello_anteprima_testo": "Ti si e' appena aperta un'anteprima del cartello. Se va bene, premi Si' per scegliere dove salvarlo definitivamente. Premi No per tornare indietro senza salvare (puoi modificare titolo/sottotitolo e generare di nuovo).",
        "ms_qr_cartello_salvato_testo": "Cartello salvato in {percorso}.",
        "ms_qr_titolo_profili": "Profili salvati",
        "ms_qr_bottone_salva_profilo": "Salva come profilo",
        "ms_qr_colonna_nome": "Nome",
        "ms_qr_colonna_ssid": "SSID",
        "ms_qr_colonna_ip": "IP",
        "ms_qr_bottone_carica_profilo": "Carica profilo",
        "ms_qr_bottone_elimina_profilo": "Elimina profilo",
        "ms_qr_errore_genera_prima_titolo": "Genera prima i QR Code",
        "ms_qr_errore_genera_prima_testo": "Premi \"Genera QR Code\" prima di salvare il profilo, cosi' le immagini vengono salvate insieme ai dati.",
        "ms_qr_profilo_esiste_titolo": "Profilo gia' esistente",
        "ms_qr_profilo_esiste_testo": "Esiste gia' un profilo chiamato \"{nome}\". Vuoi sovrascriverlo con i dati e i QR Code attuali?",
        "ms_qr_profilo_salvato_testo": "Profilo \"{nome}\" salvato: SSID, password, IP e i due QR Code sono stati archiviati.",
        "ms_qr_nessuna_selezione_titolo": "Nessun profilo selezionato",
        "ms_qr_nessuna_selezione_testo": "Seleziona prima un profilo dalla lista.",
        "ms_qr_errore_file_mancante_titolo": "File del profilo non trovato",
        "ms_qr_errore_file_mancante_testo": "Le immagini QR di questo profilo non sono state trovate sul disco (forse spostate o cancellate manualmente).",
        "ms_qr_conferma_elimina_titolo": "Eliminare il profilo?",
        "ms_qr_conferma_elimina_testo": "Eliminare definitivamente il profilo \"{nome}\" e i suoi QR Code salvati?",
        "ms_qr_etichetta_wifi": "QR WiFi",
        "ms_qr_etichetta_voto": "QR Pagina di voto",
        "ms_qr_errore_ssid_titolo": "SSID mancante",
        "ms_qr_errore_ssid_testo": "Scrivi il nome della rete WiFi (SSID) prima di generare il QR.",
        "ms_qr_errore_ip_titolo": "Indirizzo IP mancante",
        "ms_qr_errore_ip_testo": "Rileva o scrivi un indirizzo IP prima di generare il QR.",
        "ms_qr_salva_titolo": "Salva immagine QR",
        "ms_qr_salvato_testo": "Immagine salvata in:\n{percorso}",
        "ms_qr_dipendenza_mancante_titolo": "Dipendenze mancanti",
        "ms_qr_dipendenza_mancante_testo": "Per generare i QR code servono i pacchetti 'qrcode' e 'Pillow'.\n\nVuoi che li installi ora automaticamente?\n\nVerranno installati per lo stesso Python che hai usato per aprire questa finestra.",
        "ms_qr_dipendenza_installata_testo": "Pacchetti installati correttamente. Premi di nuovo \"Genera QR Code\".",

        # --- ManagerShow.pyw, scheda Storico ---
        "ms_scheda_storico": "Storico",
        "ms_storico_nota": "Voti e sequenze mandate in onda, registrati automaticamente da VotoShow.py. I voti generati dal \"Test multi-voto\" sono esclusi per default.",
        "ms_storico_label_giorno": "Giorno:",
        "ms_storico_tutto_storico": "Tutto lo storico",
        "ms_storico_checkbox_test": "Includi anche i voti di test",
        "ms_storico_bottone_aggiorna": "Aggiorna",
        "ms_storico_titolo_popolarita": "Popolarita' (classifica per numero di voti)",
        "ms_storico_colonna_titolo": "Titolo",
        "ms_storico_colonna_voti_totali": "Voti totali",
        "ms_storico_colonna_volte_vinta": "Volte mandata in onda",
        "ms_storico_titolo_cronologia": "Cronologia del giorno",
        "ms_storico_colonna_ora": "Ora",
        "ms_storico_colonna_voti_turno": "Voti ricevuti",
        "ms_storico_nota_cronologia_tutto": "Seleziona un giorno specifico per vedere la cronologia sequenziale.",
        "ms_storico_bottone_esporta": "Esporta CSV...",
        "ms_storico_esportato_titolo": "Esportato",
        "ms_storico_esportato_testo": "Dati esportati in:\n{percorso}",
        "ms_storico_bottone_elimina_giorno": "Elimina dati di questo giorno",
        "ms_storico_conferma_elimina_titolo": "Conferma eliminazione",
        "ms_storico_conferma_elimina_testo": "Eliminare definitivamente tutti i dati (voti e sequenze mandate in onda) del giorno {data}? Non si puo' annullare.",
        "ms_storico_eliminato_testo": "Dati del giorno eliminati.",
        "ms_storico_db_non_trovato": "Database storico non ancora creato: avvia VotoShow.py almeno una volta (anche solo per qualche secondo), poi torna qui e premi \"Aggiorna\".",
        "ms_storico_bottone_installa_grafico": "Installa grafico...",
        "ms_storico_grafico_mancante_testo": "Per il grafico serve il pacchetto 'matplotlib' (opzionale: il resto della scheda funziona comunque anche senza).\n\nVuoi installarlo ora automaticamente?\n\nVerra' installato per lo stesso Python che hai usato per aprire questa finestra. Dopo l'installazione va chiusa e riaperta ManagerShow.pyw perche' il grafico compaia.",
        "ms_storico_grafico_installato_testo": "'matplotlib' installato correttamente. Chiudi e riapri ManagerShow.pyw per vedere il grafico.",

        # --- ManagerShow.pyw, scheda Grafico ---
        "ms_scheda_grafico": "Grafico",
        "ms_grafico_nota": "Andamento dei voti totali giorno per giorno, nel periodo dello show che scegli qui sotto.",
        "ms_grafico_label_da": "Dal giorno:",
        "ms_grafico_label_a": "Al giorno:",
        "ms_grafico_titolo": "Voti totali per giorno",
        "ms_grafico_asse_voti": "Voti",
        "ms_grafico_nessun_dato": "Nessun dato nel periodo selezionato.",
        "ms_grafico_calendario_titolo": "Scegli una data",
        "ms_grafico_calendario_mancante_testo": "Per scegliere la data da un calendario serve il pacchetto 'tkcalendar' (opzionale: puoi comunque scrivere la data a mano o sceglierla dalla tendina).\n\nVuoi installarlo ora automaticamente?\n\nVerra' installato per lo stesso Python che hai usato per aprire questa finestra. Dopo l'installazione va chiusa e riaperta ManagerShow.pyw perche' il calendario compaia.",
        "ms_grafico_calendario_installato_testo": "'tkcalendar' installato correttamente. Chiudi e riapri ManagerShow.pyw per usare il calendario.",
        "ms_grafico_data_non_valida_titolo": "Data non valida",
        "ms_grafico_data_non_valida_testo": "Scrivi la data nel formato GG/MM/AAAA (es. 20/12/2026), oppure scegli un giorno dalla tendina o dal calendario.",
        "ms_grafico_range_salvato_testo": "Periodo salvato: la prossima volta che apri questa scheda parte gia' impostata su questo intervallo.",
    },
    "en": {
        "titolo_pagina_voto": "Request the next animation",
        "intestazione_voto": "Which animation do you want to see after this one?",
        "istruzioni_voto": "While the current animation plays you can vote as many times as you like - only your last choice counts, up until a few seconds before it ends. Requested animations will eventually play, following the queue generated by the votes.",
        "avviso_in_pausa_rifiutato": "This animation was played very recently: you can't request it again for a little while, your vote wasn't recorded.",
        "avviso_in_pausa_accettato": "This animation was played very recently: it can't start right away, but your vote still counts and it will be queued as soon as possible.",
        "avviso_coda_piena": "The queue is currently full: your vote counts for this round, but if it wins it might not find a spot in the queue.",
        "etichetta_in_pausa": "on break",
        "bottone_vota": "Request this",
        "bottone_votato": "Request sent",
        "nessuna_canzone": "No animations available right now.",
        "titolo_pagina_risultati": "Request results",
        "intestazione_risultati": "Results",
        "voti_totali": "total requests",
        "nessun_voto": "No requests yet.",
        "colonna_classifica_live": "This turn's results",
        "colonna_coda_salvata": "Queued",
        "colonna_coda_salvata_nota_turno": "The current turn always replaces the previous one: whoever votes right now wins.",
        "colonna_coda_salvata_nota_persistente": "New requests are added to the end of this list: whoever is already queued keeps their spot regardless of newer requests.",
        "colonna_coda_salvata_nota_tetto": "New requests are added to the end of this list, up to a maximum of {tetto} slots: beyond that limit they don't get queued.",
        "modalita_coda_label": "Queue mode:",
        "modalita_coda_nome_turno": "Always the latest turn (no queue)",
        "modalita_coda_nome_persistente": "Unlimited queue",
        "modalita_coda_nome_tetto": "Queue with a cap ({tetto} slots)",
        "coda_vuota": "No sequence queued right now.",
        "colonna_vincente": "Won and playing now",
        "colonna_vincente_nota": "The request ranking that started the current sequence.",
        "nessuna_vincente": "No sequence won by request right now.",
        "bottone_reset": "New round (reset requests)",
        "conferma_reset": "Reset requests to start a new round?",
        "voti_suffisso": "requests",
        "pagina_login_titolo": "Administrator access",
        "pagina_login_istruzioni": "Enter the password to view results.",
        "pagina_login_bottone": "Login",
        "pagina_login_errore": "Wrong password.",

        # --- Welcome page (VotoShow.py, before the voting page) ---
        "bv_titolo_pagina": "Welcome",
        "bv_bottone_vota": "Continue",
        "bv_bottone_ascolta": "🔊 Listen",
        "bv_bottone_pausa": "⏸ Pause",

        # --- Menu page (VotoShow.py, fork between greeting and voting) ---
        "hub_titolo_pagina": "What would you like to do?",
        "hub_intro": "Pick an option: you can do both, one after the other.",
        "hub_bottone_saluto": "🎅 Get a greeting from Santa",
        "hub_bottone_vota": "🎵 Pick your favorite animation",
        "hub_link_info": "❤️ Charity",

        # --- Info page (VotoShow.py, free-form content configurable from ManagerShow) ---
        "info_titolo_pagina": "Charity",
        "info_testo_placeholder": "This page is dedicated to charity - come back soon to find out how to contribute! 🎄",
        "info_bottone_dona": "❤️ Donate now",

        # --- Post-donation thank-you page (VotoShow.py) ---
        "grazie_titolo_pagina": "Thank you!",
        "grazie_testo_default": "Thank you so much for your contribution! ❤️ It means a lot to us and to those we help.",

        # --- Bridge page before voting (VotoShow.py) ---
        "vi_titolo_pagina": "How voting works",
        "vi_testo": "Vote for the song you want to see animated! It's a public vote: at the end of each round, the most-voted one plays. Your vote counts, but it's not a guaranteed immediate request 😊",
        "vi_bottone_continua": "Go to vote",
        "vi_bottone_indietro": "← Back to menu",

        # --- Bridge page before Santa's greeting (VotoShow.py) ---
        "sg_titolo_pagina": "Santa's greeting",
        "sg_testo": "Write your child's name: Santa will greet them by name with lights and voice, after the current sequence or the next one! Everything is generated on the spot by a dedicated computer: in rare cases there could be small technical hiccups beyond our control. Thanks for your patience, Merry Christmas! 🎄",
        "sg_bottone_continua": "Write the name",
        "sg_bottone_indietro": "← Back to menu",

        # --- Name collection page for the greeting (VotoShow.py, placeholder) ---
        "sn_titolo_pagina": "Santa's greeting",
        "sn_etichetta_nome": "Child's name:",
        "sn_bottone_invia": "Send",
        "sn_confermato_testo": "Thank you! 🎅 The greeting for {nome} has been requested.",
        "sn_confermato_nota": "(Feature still under construction: the request isn't actually processed yet.)",
        "sn_bottone_aggiungi_altro": "Greet another child",
        "sn_bottone_vai_voto": "Go to vote",
        "sn_bottone_torna_menu": "Back to menu",

        # --- CostruisciCatalogo.py (console) ---
        "cc_errore_mutagen": "ERROR: the 'mutagen' package is missing.\nInstall it with:  pip install mutagen\nthen run this script again.",
        "cc_chiedi_installazione": "Do you want me to install it now automatically? (y/n): ",
        "cc_installazione_riuscita": "'mutagen' installed successfully. Run this script again.",
        "cc_installazione_fallita": "Automatic installation failed. Try manually with: pip install mutagen",
        "cc_errore_config_mancante": "ERROR: configuration file not found: {percorso}",
        "cc_errore_cartella_sequenze_non_configurata": "ERROR: Cartella_Sequenze is not set in [PERCORSI]",
        "cc_errore_cartella_sequenze_non_trovata": "ERROR: Cartella_Sequenze not found: {percorso}",
        "cc_errore_lettura_tag": "  ! Could not read tags from '{nome}': {errore}",
        "cc_nessun_audio": "  ! '{nome}': no audio file found, sequence skipped",
        "cc_nessuna_copertina": "  ! '{nome}': no cover found, it will be shown without an image",
        "cc_scansione_di": "Scanning: {percorso}",
        "cc_cartella_esclusa": "  - '{nome}' excluded from voting (by configuration)",
        "cc_cartella_nome": "  - '{nome}'",
        "cc_catalogo_salvato": "\nCatalog saved to: {percorso}",
        "cc_canzoni_votabili": "Requestable songs: {numero}",
        "cc_attenzione_senza_copertina": "\nWarning, missing cover art (add one to the folder and run again):",

        # --- GestisciCanzoni.pyw (GUI) ---
        "gc_dipendenza_mancante_titolo": "Missing dependency",
        "gc_dipendenza_mancante_testo": "The 'mutagen' package is missing.\n\nDo you want to install it now automatically (recommended)?\n\nIt will be installed for the same Python you used to open this window, so there is no ambiguity between multiple Python installs on this PC.",
        "gc_installazione_riuscita_titolo": "Installation complete",
        "gc_installazione_riuscita_testo": "'mutagen' installed successfully.\n\nClose and reopen this window to continue.",
        "gc_installazione_fallita_titolo": "Installation failed",
        "gc_installazione_fallita_testo": "Could not install 'mutagen' automatically:\n\n{errore}\n\nTry manually from a command prompt with:\npip install mutagen",
        "gc_conferma_rinomina_titolo": "Confirm rename",
        "gc_conferma_rinomina_testo": "Rename '{vecchio}' to '{nuovo}'?\n\nLOR trigger and any voting exclusion will be moved automatically to the new name.",
        "gc_titolo_finestra": "Manage votable songs",
        "gc_titolo_dialogo_modifica": "Edit song",
        "gc_titolo_dialogo_aggiungi": "Add new song",
        "gc_campo_nome": "Name (folder):",
        "gc_campo_audio": "Audio file:",
        "gc_nessuno_scelto": "(none chosen)",
        "gc_sfoglia_audio": "Browse audio...",
        "gc_campo_titolo": "Title:",
        "gc_campo_artista": "Artist:",
        "gc_campo_copertina": "Cover:",
        "gc_nessuna": "(none)",
        "gc_sfoglia_copertina": "Browse cover...",
        "gc_campo_trigger": "LOR trigger (Network-Unit-Input):",
        "gc_campo_nome_lor": "Name in LOR (exact, for voting):",
        "gc_bottone_carica_da_lor": "Load from LOR",
        "gc_lor_non_raggiungibile_titolo": "LOR unreachable",
        "gc_lor_non_raggiungibile_testo": "Could not reach LOR's API (it must be open, even without boards connected):\n{errore}",
        "gc_lor_nessuna_sequenza_titolo": "No sequences found",
        "gc_lor_nessuna_sequenza_testo": "LOR returned no sequences in the Main. Check that the show is loaded.",
        "gc_bottone_annulla": "Cancel",
        "gc_bottone_chiudi": "Close",
        "gc_bottone_salva": "Save",
        "gc_scegli_audio": "Choose the audio file",
        "gc_scegli_copertina": "Choose the cover image",
        "gc_filtro_audio": "Audio files",
        "gc_filtro_immagini": "Images",
        "gc_filtro_tutti": "All files",
        "gc_errore_campo_obbligatorio": "Required field",
        "gc_errore_nome_vuoto": "Name cannot be empty.",
        "gc_errore_titolo_vuoto": "Title cannot be empty.",
        "gc_nome_gia_usato_titolo": "Name already in use",
        "gc_nome_gia_usato_testo": "A folder named '{nome}' already exists.",
        "gc_audio_mancante_titolo": "Missing audio file",
        "gc_audio_mancante_testo": "Choose an audio file before saving.",
        "gc_salvato_con_avvisi_titolo": "Saved with warnings",
        "gc_salvato_con_avvisi_testo": "Song saved, but rebuilding the catalog reported a problem:\n{errore}",
        "gc_promemoria_titolo": "LOR trigger reminder",
        "gc_promemoria_testo": "Remember to create/update a trigger in LOR Show Player (Interactive Group) with address:\n\n{trigger}\n\nlinked to the .loredit sequence for '{titolo}'.\nIf the .loredit file is not in the '{nome}' folder yet, add it yourself.",
        "gc_errore_titolo": "Error",
        "gc_errore_salvataggio_file": "Error saving files: {errore}",
        "gc_colonna_numero": "#",
        "gc_colonna_titolo": "Title",
        "gc_colonna_artista": "Artist",
        "gc_colonna_durata": "Duration",
        "gc_colonna_trigger": "LOR trigger",
        "gc_colonna_nome_lor": "LOR name",
        "gc_colonna_stato": "Status",
        "gc_bottone_aggiorna_lista": "Refresh list",
        "gc_bottone_aggiungi": "Add new...",
        "gc_bottone_modifica": "Edit selected...",
        "gc_bottone_escludi_includi": "Exclude/Include selected",
        "gc_bottone_rigenera": "Rebuild catalog now",
        "gc_bottone_apri_voto": "Vote",
        "gc_bottone_apri_risultati": "Open results",
        "gc_bottone_apri_benvenuto": "Welcome",
        "gc_bottone_test_multi_voto": "Multi-vote test",
        "gc_lingua_bottone": "IT",
        "ms_bottone_salva_ordine_schede": "Save tab order",
        "ms_ordine_schede_salvato_testo": "Tab order saved: it will be restored on the next launches.",
        "gc_stato_senza_audio": "No audio",
        "gc_stato_esclusa": "Excluded",
        "gc_stato_votabile": "Requestable",
        "gc_cartella_non_trovata_titolo": "Sequence folder not found",
        "gc_cartella_non_trovata_testo": "Cartella_Sequenze does not exist:\n{percorso}",
        "gc_nessuna_selezione_titolo": "No selection",
        "gc_nessuna_selezione_testo": "First select a song from the list.",
        "gc_non_modificabile_titolo": "Not editable",
        "gc_non_modificabile_testo": "This entry has no audio file to edit.",
        "gc_conferma_esclusione_titolo": "Confirm exclusion",
        "gc_conferma_esclusione_testo": "Exclude '{nome}' from voting?\n\nAudio/.loredit files stay untouched on disk: you can re-include it anytime.",
        "gc_azione_inclusa": "included in voting",
        "gc_azione_esclusa": "excluded from voting",
        "gc_attenzione_titolo": "Warning",
        "gc_attenzione_testo": "'{nome}' {azione}, but rebuilding the catalog reported a problem:\n{errore}",
        "gc_fatto_titolo": "Done",
        "gc_fatto_testo": "Catalog rebuilt. Restart VotoShow.py if it was already running during the show.",
        "gc_rigenerazione_fallita": "Catalog rebuild failed:\n{errore}",
        "gc_errore_config_generico": "Configuration error (see CONFIGURAZIONE_SHOW.ini).",

        # --- ManagerShow.pyw, Programmazione (Schedule) tab ---
        "ms_titolo_finestra": "Manager Show",
        "ms_scheda_canzoni": "Songs",
        "ms_scheda_programmazione": "Schedule",
        "ms_scheda_saluto_babbonatale": "Santa's Greeting",
        "ms_titolo_stato_attuale": "Current status",
        "ms_stato_in_esecuzione": "running",
        "ms_stato_fermo": "stopped",
        "ms_stato_motore_concluso": "check already finished (normal, it closes itself)",
        "ms_bottone_aggiorna_stato": "Refresh status",
        "ms_titolo_orari": "Schedule",
        "ms_campo_accensione": "Voting system start time (same as, or a few minutes before, the one set in LOR):",
        "ms_campo_spegnimento": "Voting system stop time (same as, or a few minutes after, the one set in LOR):",
        "ms_titolo_giorni": "Active Days",
        "ms_giorno_0": "Mon", "ms_giorno_1": "Tue", "ms_giorno_2": "Wed", "ms_giorno_3": "Thu",
        "ms_giorno_4": "Fri", "ms_giorno_5": "Sat", "ms_giorno_6": "Sun",
        "ms_titolo_pulizia": "Automatic pre-show LOR - pre-vote cleanup (closes Chrome, clears temp/cache)",
        "ms_campo_minuti_anticipo": "Minutes before Start time (VotoShow and MotoreShow, not LOR):",
        "ms_bottone_pulisci_ora": "Clean now",
        "ms_titolo_stato_pianificazione": "Automatic scheduling (Windows)",
        "ms_bottone_salva_orari": "Save schedule",
        "ms_salva_orari_promemoria_testo": "Times saved. Remember: if you want Windows to actually take them into account and apply them automatically, you need to press \"Schedule Win Auto\" right next to it - saving alone is not enough.",
        "ms_bottone_applica": "Schedule Win Auto",
        "ms_bottone_rimuovi": "Remove Win Auto",
        "ms_bottone_avvia_ora": "Start now",
        "ms_bottone_ferma_ora": "Stop now",
        "ms_avviso_avvia_ferma_testo": "Start now/Stop now only act right away, live: they don't touch Windows' automatic scheduling, which stays whatever is set in the Schedule box.",
        "ms_bottone_guida": "Guide",
        "ms_bottone_guida_pulizia": "Cleanup guide",
        "ms_titolo_chiudi_chrome": "Close Chrome",
        "ms_titolo_pulisci_cache": "Clear temp files and Chrome cache",
        "ms_titolo_blocca_aggiornamenti": "Block Windows Update",
        "ms_avviso_no_admin_titolo": "ManagerShow not elevated: automatic block not guaranteed",
        "ms_avviso_no_admin_testo": "Scheduling created (with normal permissions, to avoid an 'Access denied' error), but the automatic Windows Update block will NOT work: ManagerShow.pyw needs to be started with 'Run as administrator' right when you press this button - being an administrator account isn't enough, it needs to be elevated every time. Updates will therefore stay automatic as usual and could trigger even during the show.\n\nTo be safe: go to Settings > Windows Update > Pause updates yourself, by hand, at least 2-3 hours before Start time - or close ManagerShow and reopen it with right-click > Run as administrator, then repeat \"Schedule Win Auto\".",
        "ms_label_programmi_extra": "Programs to close automatically:",
        "ms_titolo_programmi_extra": "Programs to close",
        "ms_istruzioni_programmi_extra": "Press \"Browse...\" and find the program to close during cleanup (in the Program Files folder, or wherever you installed it, even on another drive). These programs are closed both by automatic cleanup and by \"Clean now\".",
        "ms_bottone_sfoglia_programma": "Browse...",
        "ms_filtro_eseguibili": "Programs (*.exe)",
        "ms_bottone_apri_gestione_programmi": "Add...",
        "ms_bottone_aggiungi_singolo": "Add",
        "ms_bottone_rimuovi_programma": "Remove",
        "ms_errore_orario_titolo": "Invalid time",
        "ms_errore_orario_accensione_testo": "Start time must be HH:MM (e.g. 17:30).",
        "ms_errore_orario_spegnimento_testo": "Stop time must be HH:MM (e.g. 22:30).",
        "ms_errore_nessun_giorno_titolo": "No day selected",
        "ms_errore_nessun_giorno_testo": "Select at least one active day.",
        "ms_errore_minuti_titolo": "Invalid value",
        "ms_errore_minuti_testo": "Minutes before must be a number (e.g. 15).",
        "ms_conferma_titolo": "Confirm",
        "ms_pianificazione_applicata_testo": "Scheduling applied: cleanup at {orario}, voting system turns on/off automatically at the set times.",
        "ms_pianificazione_fallita_testo": "Could not register the scheduling:\n\n{dettagli}",
        "ms_prefisso_avvio": "Start",
        "ms_prefisso_stop": "Stop",
        "ms_prefisso_pulizia": "Cleanup",
        "ms_conferma_rimozione_testo": "Remove automatic scheduling? You will need to start/stop everything manually.",
        "ms_pianificazione_rimossa_testo": "Scheduling removed.",
        "ms_stato_pianificazione_attiva": "Windows scheduling ACTIVE: cleanup, voting system start and stop are automatic.",
        "ms_stato_pianificazione_non_attiva": "Windows scheduling NOT active: start/stop is manual only.",
        "ms_pulizia_eseguita_testo": "Cleanup done (Chrome closed, temp/cache files cleared, if enabled).",

        # --- ManagerShow.pyw, Schedule tab: vote queue mode ---
        "ms_titolo_modalita_coda": "Vote queue mode",
        "ms_modalita_coda_label": "How to handle the queue:",
        "ms_modalita_coda_turno": "Always the latest turn (no queue)",
        "ms_modalita_coda_persistente": "Unlimited queue (never dropped)",
        "ms_modalita_coda_tetto": "Queue with a maximum cap",
        "ms_tetto_coda_label": "Maximum cap (queue slots):",
        "ms_nota_modalita_coda_turno": "No queue: only whoever votes right now wins, whoever loses a turn never sees their pick play if people keep voting. Requires restarting VotoShow.py.",
        "ms_nota_modalita_coda_persistente": "Whoever wins a turn is never dropped by more recent votes, but on busy nights the wait can grow quite long. Requires restarting VotoShow.py.",
        "ms_nota_modalita_coda_tetto": "A middle ground: the maximum wait stays capped at the value below, beyond that limit extra turns don't get queued. Requires restarting VotoShow.py.",
        "ms_bottone_salva_modalita_coda": "Save queue mode",
        "ms_modalita_coda_salvata_testo": "Queue mode saved. Restart VotoShow.py (Stop now / Start now) for it to take effect.",
        "ms_modalita_coda_riavvia_ora_titolo": "Restart VotoShow.py now?",
        "ms_modalita_coda_riavvia_ora_testo": "VotoShow.py is running. Do you want to restart it now to apply the new queue mode?\n\nDuring the restart (a few seconds) the voting service will be unreachable for guests.",
        "ms_modalita_coda_riavviato_testo": "Queue mode saved and VotoShow.py restarted: the new mode is already active.",
        "ms_errore_tetto_titolo": "Invalid value",
        "ms_errore_tetto_testo": "The maximum cap must be a whole number of at least 1.",
        "ms_raffreddamento_label": "Cooldown (break after playing):",
        "ms_raffreddamento_turni": "Number of sequences",
        "ms_raffreddamento_minuti": "Minutes",
        "ms_raffreddamento_valore_label": "Value:",
        "ms_errore_raffreddamento_titolo": "Invalid value",
        "ms_errore_raffreddamento_testo": "The cooldown value must be a whole number of at least 1.",
        "ms_avviati_testo": "VotoShow.py and MotoreShow.py started (if not already running).",
        "ms_fermati_testo": "VotoShow.py and MotoreShow.py stopped (if they were running).",

        # --- ManagerShow.pyw, Schedule tab: Santa's greeting (optional) ---
        "ms_titolo_saluto_babbonatale": "Santa's greeting (optional)",
        "ms_checkbox_saluto_babbonatale": "Enable the personalized name greeting",
        "ms_nota_saluto_babbonatale": "Optional feature: if disabled, guests only see the voting page, no extra fork. If enabled, before voting an extra choice appears letting a parent type their child's name and get a personalized greeting (lights + voice) from Santa. NOTE: right now this is only the on/off switch and the interface - the actual greeting generation (the name animation and audio) is still under development and requires an external text-to-speech service (e.g. ElevenLabs) configured separately. See the Guide button for details.",
        "ms_bottone_salva_saluto_babbonatale": "Save greeting setting",
        "ms_saluto_babbonatale_salvata_testo": "Setting saved. Restart VotoShow.py (Stop now / Start now) for it to take effect.",
        "ms_saluto_babbonatale_riavvia_ora_titolo": "Restart VotoShow.py now?",
        "ms_saluto_babbonatale_riavvia_ora_testo": "VotoShow.py is running. Do you want to restart it now to apply the new setting?\n\nDuring the restart (a few seconds) the voting service will be unreachable for guests.",
        "ms_saluto_babbonatale_riavviato_testo": "Setting saved and VotoShow.py restarted: it's already active.",

        # --- ManagerShow.pyw, Schedule tab: admin token ---
        "ms_titolo_token_admin": "Admin token",
        "ms_label_token_admin": "Token:",
        "ms_bottone_mostra_token": "Show",
        "ms_bottone_nascondi_token": "Hide",
        "ms_bottone_genera_token": "Generate random",
        "ms_nota_token_admin": "Protects the /risultati and /reset pages of the voting server (reachable on the guest WiFi). If left empty, anyone on the network can access them with no password: not recommended. Use 'Generate random' to create a strong one, then save. After saving, VotoShow.py needs a restart for the new token to take effect.",
        "ms_bottone_salva_token": "Save token",
        "ms_token_admin_vuoto_titolo": "Save without a token?",
        "ms_token_admin_vuoto_testo": "The field is empty: /risultati and /reset will stay open to anyone on the guest WiFi, with no password. Save anyway?",
        "ms_token_admin_salvato_testo": "Token saved. Restart VotoShow.py (Stop now / Start now) for it to take effect.",
        "ms_token_admin_riavvia_ora_titolo": "Restart VotoShow.py now?",
        "ms_token_admin_riavvia_ora_testo": "VotoShow.py is running. Do you want to restart it now to apply the new token?\n\nDuring the restart (a few seconds) the voting service will be unreachable for guests.",
        "ms_token_admin_riavviato_testo": "Token saved and VotoShow.py restarted: it's already active.",

        # --- Multi-vote test (opens several isolated windows to simulate several voters) ---
        "ms_test_voto_titolo_dialogo": "Multi-vote test",
        "ms_test_voto_prompt": "How many windows do you want to open for the test? (each one counts as a different voter)",
        "ms_test_voto_richiede_avvio_titolo": "VotoShow.py is not running",
        "ms_test_voto_richiede_avvio_testo": "Start VotoShow.py first (\"Start now\") before opening the test windows.",
        "ms_test_voto_browser_non_trovato_titolo": "Browser not found",
        "ms_test_voto_browser_non_trovato_testo": "I couldn't find Google Chrome or Microsoft Edge installed in a standard location: one of them is needed to open windows with separate profiles (independent cookies). Install one of the two, or manually open several different browsers for the test.",
        "ms_test_voto_aperte_testo": "Opened {numero} test windows at http://127.0.0.1:{porta}/vota, each with its own cookies (separate voter). The 2-second anti-spam limit between votes is disabled only for these local windows.",

        # --- ManagerShow.pyw, Welcome Page tab ---
        "ms_scheda_benvenuto": "Welcome Page",
        "ms_tooltip_percorso_schede_luci": "Point to SchedeLuci.pyw if you moved its folder.",
        "ms_bv_nota_scheda": "This is the first page guests see (e.g. redirected here by Wi-Fi), before reaching the actual voting page. All fields are optional.",
        "ms_bv_titolo_testo": "Text",
        "ms_bv_nota_testo": "Leave a blank line between two blocks of text to create separate paragraphs, each with its own spacing (e.g. a title with a subtitle set apart below it). A single line break within the same block stays a simple line break.",
        "ms_bv_titolo_immagine": "Background image",
        "ms_bv_campo_immagine": "Image file:",
        "ms_bv_bottone_sfoglia_immagine": "Browse...",
        "ms_bv_bottone_rimuovi_immagine": "Remove",
        "ms_bv_scegli_immagine_titolo": "Choose the background image",
        "ms_bv_filtro_immagini": "Images (*.jpg;*.jpeg;*.png;*.gif)",
        "ms_bv_titolo_audio": "Audio (optional)",
        "ms_bv_campo_audio": "Audio file:",
        "ms_bv_bottone_sfoglia_audio": "Browse...",
        "ms_bv_bottone_rimuovi_audio": "Remove",
        "ms_bv_scegli_audio_titolo": "Choose the audio file",
        "ms_bv_filtro_audio": "Audio (*.mp3)",
        "ms_bv_nessuna_scelta": "(none chosen)",
        "ms_bv_titolo_colore": "Text band color",
        "ms_bv_bottone_cambia_colore": "Change color...",
        "ms_bv_nota_colore": "Automatically suggested from the chosen image (if Pillow is installed); you can still change it by hand.",
        "ms_bv_bottone_salva": "Save welcome page",
        "ms_bv_bottone_anteprima": "Open preview in browser",
        "ms_bv_salvato_titolo": "Saved",
        "ms_bv_salvato_testo": "Welcome page saved. If VotoShow.py is already running during the show, restart it (Stop now / Start now in the Schedule tab) for the changes to take effect.",
        "ms_bv_pillow_mancante_titolo": "Optional dependency missing",
        "ms_bv_pillow_mancante_testo": "Automatically suggesting a color from the image needs the 'Pillow' package (not required: you can still pick the color by hand with 'Change color...').\n\nDo you want to install it now automatically?\n\nIt will be installed for the same Python you used to open this window.",
        "ms_bv_pillow_installata_testo": "'Pillow' installed correctly. Choose the image again to get a suggested color.",

        # --- ManagerShow.pyw, Info tab (free-form page reachable from the menu, e.g. for charity/sponsor/rules) ---
        "ms_scheda_info": "Charity",
        "ms_inf_nota_scheda": "Optional page reachable from the guest menu (the \"❤️ Charity\" link): use it for whatever you want - a donation link, a charity, a sponsor, show rules, etc. Same structure as the Welcome page (text, image, audio), but meant to be revisited when needed, not just seen once on entry. If you leave every field empty, the link disappears entirely for guests.",
        "ms_inf_titolo_testo": "Text",
        "ms_inf_nota_testo": "Leave a blank line between two blocks of text to create separate paragraphs, each with its own spacing. A single line break within the same block stays a simple line break.",
        "ms_inf_titolo_immagine": "Image",
        "ms_inf_campo_immagine": "Image file:",
        "ms_inf_bottone_sfoglia_immagine": "Browse...",
        "ms_inf_bottone_rimuovi_immagine": "Remove",
        "ms_inf_scegli_immagine_titolo": "Choose the image",
        "ms_inf_filtro_immagini": "Images (*.jpg;*.jpeg;*.png;*.gif)",
        "ms_inf_titolo_audio": "Audio (optional)",
        "ms_inf_campo_audio": "Audio file:",
        "ms_inf_bottone_sfoglia_audio": "Browse...",
        "ms_inf_bottone_rimuovi_audio": "Remove",
        "ms_inf_scegli_audio_titolo": "Choose the audio file",
        "ms_inf_filtro_audio": "Audio (*.mp3)",
        "ms_inf_titolo_colore": "Text band color",
        "ms_inf_bottone_cambia_colore": "Change color...",
        "ms_inf_nota_colore": "Automatically suggested from the chosen image (if Pillow is installed); you can still change it by hand.",
        "ms_inf_titolo_visibilita": "Visibility",
        "ms_inf_checkbox_visibile": "Page visible to guests (\"❤️ Charity\" link in the menu)",
        "ms_inf_nota_visibilita": "The only switch that matters: if checked, the link shows up for guests even if you haven't written anything yet (they'll see a generic \"page coming soon\" message). If NOT checked, the link stays fully hidden, no matter what you've already filled in below - handy for preparing content at your own pace before publishing it.",
        "ms_inf_titolo_donazione": "Donation link",
        "ms_inf_campo_link_donazione": "Payment page URL (Stripe, PayPal, other):",
        "ms_inf_nota_donazione": "If filled in, a \"❤️ Donate now\" button appears on the Charity page linking to this address (opens in a new tab). The easiest way to get one without writing code: a Stripe 'Payment Link' or a 'PayPal.me' link - you create it on the chosen service's site and paste the URL they give you here. For something more custom (a personalized payment page, tracking, etc.) you'll need to write code: if you're not comfortable with that, getting help from an AI (e.g. Claude, ChatGPT) for this part is a great way to get it done anyway, just explain what you want to achieve. See the Guide button for Stripe/PayPal details.",
        "ms_inf_titolo_grazie": "Thank-you page",
        "ms_inf_nota_grazie": "Text shown after a donation, on a separate page (address /grazie) - useful if your chosen payment service lets you set a custom return address after payment (both Stripe Checkout and PayPal support this). If you leave this empty, a ready-made generic thank-you message is shown instead. Follows the same \"Visible\" checkbox above - no separate switch.",
        "ms_inf_bottone_anteprima_grazie": "Open thank-you preview",
        "ms_inf_bottone_salva": "Save Charity page",
        "ms_inf_bottone_anteprima": "Open preview in browser",
        "ms_inf_salvato_titolo": "Saved",
        "ms_inf_salvato_testo": "Charity page saved. If VotoShow.py is already running during the show, restart it (Stop now / Start now in the Schedule tab) for the changes to take effect.",

        # --- ManagerShow.pyw, QR Code tab ---
        "ms_scheda_qrcode": "QR Code",
        "ms_qr_nota_scheda": "Generate two QR codes ready to print near the show: one to join the guest WiFi (the phone does it on its own, no typing a password by hand), one to open the voting page right away. Both created on your own PC, no external site involved: the WiFi password never leaves here.",
        "ms_qr_titolo_wifi": "Guest WiFi",
        "ms_qr_campo_ssid": "Network name (SSID):",
        "ms_qr_campo_password": "Password:",
        "ms_qr_campo_sicurezza": "Security:",
        "ms_qr_sicurezza_wpa": "WPA/WPA2",
        "ms_qr_sicurezza_wep": "WEP",
        "ms_qr_sicurezza_nessuna": "None (open network)",
        "ms_qr_titolo_indirizzo": "Voting page address",
        "ms_qr_campo_ip": "IP address:",
        "ms_qr_nota_ip": "Auto-detected from this PC's network - if you have more than one network adapter and it's not the right one, correct it by hand. It must be the IP guests can reach from the WiFi network, not 127.0.0.1.",
        "ms_qr_bottone_rileva_ip": "Detect again",
        "ms_qr_bottone_genera": "Generate QR Codes",
        "ms_qr_bottone_salva_wifi": "Save WiFi image...",
        "ms_qr_bottone_salva_voto": "Save Voting image...",
        "ms_qr_titolo_cartello": "Printable poster",
        "ms_qr_campo_cartello_titolo": "Title:",
        "ms_qr_campo_cartello_sottotitolo": "Subtitle:",
        "ms_qr_checkbox_cartello_includi_voto": "Include the voting page QR (step 2)",
        "ms_qr_bottone_genera_cartello": "Generate printable poster",
        "ms_qr_bottone_stampa_cartello": "Print poster",
        "ms_qr_dipendenza_stampa_mancante_testo": "Direct printing needs the 'pywin32' package.\n\nDo you want to install it now automatically?\n\nIt will be installed for the same Python used to open this window.",
        "ms_qr_conferma_stampa_titolo": "Print now?",
        "ms_qr_conferma_stampa_testo": "A preview of the poster just opened. If it looks good, it will be printed on the default printer: {stampante}.\n\nProceed?",
        "ms_qr_stampa_titolo": "Print sent",
        "ms_qr_stampa_inviata_testo": "The poster was sent to {stampante}.",
        "ms_qr_cartello_sottotitolo_default": "Request your favorite animated sequence!",
        "ms_qr_cartello_passo1": "1. Connect to the Wi-Fi",
        "ms_qr_cartello_passo2": "2. Pick your sequence",
        "ms_qr_cartello_rete": "Network: {rete}",
        "ms_qr_cartello_password": "Password: {password}",
        "ms_qr_cartello_nota_wifi": "(scan this one first)",
        "ms_qr_cartello_nota_voto": "(scan this one after connecting to the Wi-Fi)",
        "ms_qr_cartello_anteprima_titolo": "Does it look right?",
        "ms_qr_cartello_anteprima_testo": "A preview of the poster just opened. If it looks good, press Yes to choose where to save it for good. Press No to go back without saving (you can edit title/subtitle and generate again).",
        "ms_qr_cartello_salvato_testo": "Poster saved to {percorso}.",
        "ms_qr_titolo_profili": "Saved profiles",
        "ms_qr_bottone_salva_profilo": "Save as profile",
        "ms_qr_colonna_nome": "Name",
        "ms_qr_colonna_ssid": "SSID",
        "ms_qr_colonna_ip": "IP",
        "ms_qr_bottone_carica_profilo": "Load profile",
        "ms_qr_bottone_elimina_profilo": "Delete profile",
        "ms_qr_errore_genera_prima_titolo": "Generate the QR Codes first",
        "ms_qr_errore_genera_prima_testo": "Press \"Generate QR Code\" before saving the profile, so the images get saved together with the data.",
        "ms_qr_profilo_esiste_titolo": "Profile already exists",
        "ms_qr_profilo_esiste_testo": "A profile named \"{nome}\" already exists. Overwrite it with the current data and QR Codes?",
        "ms_qr_profilo_salvato_testo": "Profile \"{nome}\" saved: SSID, password, IP and both QR Codes have been archived.",
        "ms_qr_nessuna_selezione_titolo": "No profile selected",
        "ms_qr_nessuna_selezione_testo": "Select a profile from the list first.",
        "ms_qr_errore_file_mancante_titolo": "Profile files not found",
        "ms_qr_errore_file_mancante_testo": "This profile's QR images were not found on disk (maybe moved or deleted manually).",
        "ms_qr_conferma_elimina_titolo": "Delete this profile?",
        "ms_qr_conferma_elimina_testo": "Permanently delete the profile \"{nome}\" and its saved QR Codes?",
        "ms_qr_etichetta_wifi": "WiFi QR",
        "ms_qr_etichetta_voto": "Voting page QR",
        "ms_qr_errore_ssid_titolo": "SSID missing",
        "ms_qr_errore_ssid_testo": "Type the WiFi network name (SSID) before generating the QR code.",
        "ms_qr_errore_ip_titolo": "IP address missing",
        "ms_qr_errore_ip_testo": "Detect or type an IP address before generating the QR code.",
        "ms_qr_salva_titolo": "Save QR image",
        "ms_qr_salvato_testo": "Image saved to:\n{percorso}",
        "ms_qr_dipendenza_mancante_titolo": "Missing dependencies",
        "ms_qr_dipendenza_mancante_testo": "Generating QR codes needs the 'qrcode' and 'Pillow' packages.\n\nDo you want me to install them now automatically?\n\nThey'll be installed for the same Python you used to open this window.",
        "ms_qr_dipendenza_installata_testo": "Packages installed successfully. Press \"Generate QR Codes\" again.",

        # --- ManagerShow.pyw, History tab ---
        "ms_scheda_storico": "History",
        "ms_storico_nota": "Votes and sequences played, recorded automatically by VotoShow.py. Votes generated by \"Multi-vote test\" are excluded by default.",
        "ms_storico_label_giorno": "Day:",
        "ms_storico_tutto_storico": "Entire history",
        "ms_storico_checkbox_test": "Include test votes too",
        "ms_storico_bottone_aggiorna": "Refresh",
        "ms_storico_titolo_popolarita": "Popularity (ranked by vote count)",
        "ms_storico_colonna_titolo": "Title",
        "ms_storico_colonna_voti_totali": "Total votes",
        "ms_storico_colonna_volte_vinta": "Times played",
        "ms_storico_titolo_cronologia": "Day timeline",
        "ms_storico_colonna_ora": "Time",
        "ms_storico_colonna_voti_turno": "Votes received",
        "ms_storico_nota_cronologia_tutto": "Select a specific day to see the sequential timeline.",
        "ms_storico_bottone_esporta": "Export CSV...",
        "ms_storico_esportato_titolo": "Exported",
        "ms_storico_esportato_testo": "Data exported to:\n{percorso}",
        "ms_storico_bottone_elimina_giorno": "Delete this day's data",
        "ms_storico_conferma_elimina_titolo": "Confirm deletion",
        "ms_storico_conferma_elimina_testo": "Permanently delete all data (votes and played sequences) for {data}? This cannot be undone.",
        "ms_storico_eliminato_testo": "Day's data deleted.",
        "ms_storico_db_non_trovato": "History database not created yet: start VotoShow.py at least once (even just for a few seconds), then come back here and press \"Refresh\".",
        "ms_storico_bottone_installa_grafico": "Install chart...",
        "ms_storico_grafico_mancante_testo": "The chart needs the 'matplotlib' package (optional: the rest of the tab still works fine without it).\n\nDo you want to install it now automatically?\n\nIt will be installed for the same Python you used to open this window. After installing, close and reopen ManagerShow.pyw for the chart to appear.",
        "ms_storico_grafico_installato_testo": "'matplotlib' installed correctly. Close and reopen ManagerShow.pyw to see the chart.",

        # --- ManagerShow.pyw, Chart tab ---
        "ms_scheda_grafico": "Chart",
        "ms_grafico_nota": "Total votes per day, over the show period you choose below.",
        "ms_grafico_label_da": "From day:",
        "ms_grafico_label_a": "To day:",
        "ms_grafico_titolo": "Total votes per day",
        "ms_grafico_asse_voti": "Votes",
        "ms_grafico_nessun_dato": "No data in the selected period.",
        "ms_grafico_calendario_titolo": "Choose a date",
        "ms_grafico_calendario_mancante_testo": "Picking the date from a calendar needs the 'tkcalendar' package (optional: you can still type the date by hand or pick it from the dropdown).\n\nDo you want to install it now automatically?\n\nIt will be installed for the same Python you used to open this window. After installing, close and reopen ManagerShow.pyw for the calendar to appear.",
        "ms_grafico_calendario_installato_testo": "'tkcalendar' installed correctly. Close and reopen ManagerShow.pyw to use the calendar.",
        "ms_grafico_data_non_valida_titolo": "Invalid date",
        "ms_grafico_data_non_valida_testo": "Type the date as DD/MM/YYYY (e.g. 20/12/2026), or pick a day from the dropdown or the calendar.",
        "ms_grafico_range_salvato_testo": "Period saved: next time you open this tab it will already start set to this range.",
    },
}


def testo(lingua: str, chiave: str, **valori) -> str:
    dizionario = TESTI.get(lingua, TESTI[LINGUA_DEFAULT])
    modello = dizionario.get(chiave, TESTI[LINGUA_DEFAULT].get(chiave, chiave))
    return modello.format(**valori) if valori else modello
